# Generated by Django 5.2.7 on 2025-10-27 15:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр объявления',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('price_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Pound Sterling'), ('CHF', 'Swiss Franc'), ('PLN', 'Polish Zloty'), ('CZK', 'Czech Koruna')], default='EUR', max_length=3, verbose_name='Валюта')),
                ('property_type', models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('studio', 'Студия'), ('room', 'Комната')], default='apartment', max_length=20, verbose_name='Тип жилья')),
                ('rooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('is_available', models.BooleanField(default=True, verbose_name='Активно')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='locations.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
