# Generated by Django 5.2.7 on 2025-10-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.user', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listing', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('owner', 'title', 'street', 'house_number', 'apartment_number'), name='unique_owner_listing_address'),
        ),
    ]
