# Generated by Django 5.2.6 on 2025-10-23 11:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_alter_listing_apartment_number_and_more'),
        ('locations', '0002_alter_city_options_alter_country_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр объявления',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('owner', 'title', 'street', 'house_number', 'apartment_number'), name='unique_owner_listing_address'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listing', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
