# Generated by Django 5.2.6 on 2025-10-25 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingview_alter_listing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('studio', 'Студия'), ('room', 'Комната')], default='apartment', max_length=20, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
