# Generated by Django 5.2.6 on 2025-10-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь.', related_name='user_groups', to='auth.group', verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Конкретные права пользователя.', related_name='user_permissions_set', to='auth.permission', verbose_name='права пользователя'),
        ),
    ]
