# Generated by Django 5.2.6 on 2025-10-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_check_in_time_booking_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
