# Generated by Django 5.2.6 on 2025-10-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state'),
        ),
    ]
